<div class="row-fluid col-md-12">
		<?php
			if(isset($_SESSION['isAdmin']))
			{
				if(isset($_GET['check_ssh']))
				{
					include("./includes/content_left/check_ssh.php"); 
				}
				else
				if(isset($_GET['invoice']))
				{
					if($_GET['invoice']=="history")
					{
						include("./includes/content_left/history_invoice.php"); 

					}
					else
					{
						include("./includes/content_left/invoice.php"); 
					}
					/*
						if($_GET['invoice']=="week")
						{
							include("./includes/content_left/invoice_w.php"); 
						}
						else
						{
							include("./includes/content_left/invoice_m.php"); 
						}
					*/
				}
				else
				if(isset($_GET['managerapp']))
				{
					include("./includes/content_left/managerapp.php"); 
				}
				else
				if(isset($_GET['category']))
				{
					include("./includes/content_left/category.php"); 
				}
				else
				if(isset($_GET['offers']))
				{
					if($_GET['offers']=="table")
					{
						include("./includes/content_left/offers_table.php"); 
					}
					else
					if($_GET['offers']=="ios")
					{
						include("./includes/content_left/offers_ios.php"); 
					}
					else
					if($_GET['offers']=="pc")
					{
						include("./includes/content_left/offers_pc.php"); 
					}
					else
					if($_GET['offers']=="wall")
					{
						include("./includes/content_left/offers_wall.php"); 
					}
					else
					{
						include("./includes/content_left/offers_android.php"); 
					}
				}
				else
				if(isset($_GET['mods']))
				{
					include("./includes/content_left/mods.php"); 
				}
				else
				if(isset($_GET['users']))
				{
					include("./includes/content_left/users.php"); 
				}
				else
				if(isset($_GET['networks']))
				{
					include("./includes/content_left/networks.php"); 
				}
				else
				if(isset($_GET['report'])&&$_GET['report']=="clicks")
				{
					include("./includes/content_left/report_clicks.php"); 
				}
				else
				if(isset($_GET['report'])&&$_GET['report']=="leads")
				{
					include("./includes/content_left/report_leads.php"); 
				}
				else
				if(isset($_GET['report'])&&$_GET['report']=="offers")
				{
					include("./includes/content_left/report_offers.php"); 
				}
				else
				if(isset($_GET['settings']))
				{
					include("./includes/content_left/settings.php"); 
				}
				else
				if(isset($_GET['api_get_app']))
				{
						include("./includes/content_left/api_".$_GET['api_get_app'].".php"); 
				}
				else
				{
					include("./includes/content_left/dashboard.php");
				}
			}
			if(isset($_SESSION['isMod']))
			{
				$groupName=$_SESSION['groupName'];
				if(isset($_GET['check_ssh']))
				{
					include("./includes/content_left/check_ssh.php"); 
				}
				else
				if(isset($_GET['users']))
				{
					include("./includes/content_left/users_mod.php"); 
				}
				else
				if(isset($_GET['report'])&&$_GET['report']=="clicks")
				{
					include("./includes/content_left/report_clicks_mod.php"); 
				}
				else
				if(isset($_GET['report'])&&$_GET['report']=="leads")
				{
					include("./includes/content_left/report_leads_mod.php"); 
				}
				else
				if(isset($_GET['report'])&&$_GET['report']=="offers")
				{
					include("./includes/content_left/report_offers_mod.php"); 
				}
				else
				if(isset($_GET['settings']))
				{
					include("./includes/content_left/settings_mod.php"); 
				}
				else
				if(isset($_GET['invoice']))
				{
					include("./includes/content_left/history_invoice_mod.php"); 
				}
				else
				{
					include("./includes/content_left/dashboard_mod.php");
				}
			}
			if(isset($_SESSION['isMember']))
			{
				if(isset($_GET['report']))
				{
					if($_GET['report']=="clicks")
					{
						include("./includes/content_left/report_clicks_mem.php"); 
					}
					else
					if($_GET['report']=="leads")
					{
						include("./includes/content_left/report_leads_mem.php"); 
					}
					else
					if($_GET['report']=="offers")
					{
						include("./includes/content_left/report_offers_mem.php"); 
					}
				}
				else
				if(isset($_GET['settings']))
				{
					include("./includes/content_left/settings_member.php"); 
				}
				else
				if(isset($_GET['invoice']))
				{
					include("./includes/content_left/history_invoice_mem.php"); 
				}
				else
				if(isset($_GET['check_ssh']))
				{
					include("./includes/content_left/check_ssh.php"); 
				}
				else
				if(isset($_GET['earns']))
				{
					include("./includes/content_left/earns.php"); 
				}
				else
				{
					include("./includes/content_left/statistic.php");
				}
			}
		?>
</div>
